### ISSUE TITLE
Two small CSS fixes player sheet (css inside)

### ISSUE THREAD

**Issue by yjeroen** [pwatson100/symbaroum#451]
Providing CSS like this as I havent installed/used GIT in 1.5 years. :)

```css
.symbaroum.sheet.actor .player .sheet-header input {
    width: 30px;
}
.symbaroum.sheet.actor .player .main .combat .combatheader .iniheader .title {
	font-size: 14px;
    font-weight: bold;
    color: var(--color-label);
    font-family: var(--font-text);
	line-height: 1.3em;
}
```

**Comment by bithir** [comment]
Can you remind us what this was for and if it is still required?

**Comment by yjeroen** [comment]
It's to better outline character sheet fields.

**Comment by bithir** [comment]
I am reluctant for the following:
width: 30px;
Currently we are using 4 ems, which scales better and matches the other fields on the page - 30 px is also not enough on my screen to fit in all characters for iniatitive.
Sample:
![image](https://user-images.githubusercontent.com/19734037/194387525-ad89f9fb-809c-43ee-a32e-11f32a6ddb3f.png)

**Comment by bithir** [comment]
I changed the following:
```css
.symbaroum.sheet.actor .player .main .combat .combatheader .iniheader .title {
  color: var(--color-title);
  font-weight: bold;
  font-family: var(--font-text);
  text-align: center;
  padding: 5px;
}

```
The color is already there, using `--color-title` and the line-height does not seem to do any difference, so not sure why it is required.
