### ISSUE TITLE
CSS player sheet mobile phone (css inside)

### ISSUE THREAD

**Issue by yjeroen** [pwatson100/symbaroum#452]
Providing CSS like this as I havent installed/used GIT in 1.5 years. :)
Works best together with Mobile Improvements module.

```css
@media(max-width: 650px) {
	.window-app .window-content {
		padding: 0px;
	}
	.symbaroum.sheet.actor h1 {
		padding: 0 5px;
	}
	.symbaroum.sheet.actor .player .main .combat .weapons .item-list .weapon, .symbaroum.sheet.actor .player .main .combat .armor .item-row {
		background-color: black;
	}
	.symbaroum.sheet.actor .image-container {
		background: none;
	}
	.symbaroum.sheet.actor .player .main .abilities-powers .traits .trait {
		width: calc(100%);
	}
	.symbaroum.sheet.actor .player .main .combat .weapons .item-header {
		margin-top: 0px;
	}
	.symbaroum.sheet.actor .player .sheet-header .wrapper-row {
		flex-direction: column;
	}
	.symbaroum.sheet.actor .player .sheet-header .name, .symbaroum.sheet.actor .player .sheet-header .race {
		margin-right: 0;
	}
	.symbaroum.sheet.actor .player .sheet-header .experience, .symbaroum.sheet.actor .player .sheet-header .occupation {
		margin-left: 0;
	}
	.symbaroum.sheet.actor .player .main .health2, .symbaroum.sheet.actor .health-corruptioncol {
		flex-direction: column;
		flex-basis: calc(100%);
		margin-left: 0px;
	}
	.symbaroum.sheet.actor .player .main .combat {
		margin-left: 0px;
	}
	.symbaroum.sheet.actor .toughness {
		flex-basis: calc(100%);
		padding-bottom: 5px;
	}
	.symbaroum.sheet.actor .health-toughnesscol {
		flex-basis: calc(100%);
		margin-right: 0px;
	}
	.symbaroum.sheet.actor .player .main .health2 .toughness-current, .symbaroum.sheet.actor .player .main .health2 .toughness-total, .symbaroum.sheet.actor .player .main .health2 .toughness-threshold {
		flex-basis: calc(33% - 9px);
		height: 38px;
	    padding: 5px 0;
	}
	.symbaroum.sheet.actor .health2 label {
		width: 7em;
	}
	.symbaroum.sheet.actor .player .main .combat .armor .roll-armor div:nth-child(2), .symbaroum.sheet.actor .player .main .combat .weapons .roll-weapon div:nth-child(2) {
		display: none;
	}
	.symbaroum.sheet.actor .player .main .abilities-powers .traits {
		flex-direction: column;
		height: auto;
		overflow: hidden;
		margin: 5px 0;
	}
	.symbaroum.sheet.actor .player .main .abilities-powers {
		height: fit-content;
		padding-bottom: 5px;
	}
	.symbaroum.sheet.actor .player .gear .wrapper-left .armors .armor td .armorname, .symbaroum.sheet.actor .player .gear .wrapper-left .weapons .weapon td .weaponname, .symbaroum.sheet.actor .player .gear .wrapper-left .artifacts .artifact td .artifactname {
		min-width: 0;
	}
	.symbaroum.sheet.actor .player .gear {
		flex-direction: column;
	}
	.symbaroum.sheet.actor .player .gear .wrapper-left .armors, .symbaroum.sheet.actor .player .gear .wrapper-left .weapons, .symbaroum.sheet.actor .player .gear .wrapper-left .artifacts, .symbaroum.sheet.actor .player .gear .wrapper-right .equipments {
		height: 100%;
		min-height: 80px;
	}
	.symbaroum.sheet.actor .player .gear .wrapper-right {
		margin-top: 10px;
		margin-left: 0px;
	}
	.symbaroum.sheet.actor .player .main .combat .weapons {
		height: 100%;
	}
	.symbaroum.sheet.actor .item-list .items {
		overflow: hidden;
	}
	
	.symbaroum.sheet.actor .player .gear .wrapper-left .armors .armor td.state .item-state, .symbaroum.sheet.actor .player .gear .wrapper-left .weapons .weapon td.state .item-state, .symbaroum.sheet.actor .player .gear .wrapper-left .artifacts .artifact td.state .item-state, .symbaroum.sheet.actor .player .gear .wrapper-right .equipments .equipment td.state .item-state {
		padding-left: 5px;
	}
	.symbaroum.sheet.actor .player .gear .wrapper-left .armors .armor td.button .item-delete, .symbaroum.sheet.actor .player .gear .wrapper-left .weapons .weapon td.button .item-delete, .symbaroum.sheet.actor .player .gear .wrapper-left .artifacts .artifact td.button .item-delete, .symbaroum.sheet.actor .player .gear .wrapper-right .equipments .equipment td.button .item-delete {
		padding: 0 5px;
	}
	.symbaroum.sheet.actor .player .main .combat .armor .roll-armor .combatProt, .symbaroum.sheet.actor .player .main .combat .weapons .roll-weapon .weaponDam {
		width: 6em;
		min-width: 6em;
	}
	.symbaroum.sheet.actor .player .section1 {
		flex-direction: column; 
	}
	.symbaroum.sheet.actor .player .main .attributes, .symbaroum.sheet.actor .health-corruptioncol {
		width: calc(100%);
		display: flex;
		flex-wrap: wrap;
		margin-bottom: 5px;
	}
	.symbaroum.sheet.actor .player .main .attributes .attributes-header {
		flex: 100%;
	}
	.symbaroum.sheet.actor .player .main .attributes .attribute {
		flex: 45%;
		height: 28px;
	}	
	.symbaroum.sheet.actor .health-corruptioncol {
		flex-direction: row;
		margin-top: 5px;
	}
	.symbaroum.sheet.actor .player .main .health2 .corruption .health-corruptioncol .corruption-col1 div, .symbaroum.sheet.actor .player .main .health2 .corruption .health-corruptioncol .corruption-col2 div {
		flex: 45%;
		height: 28px;
	}
	.symbaroum.sheet.actor .nonattributes {
		flex-basis: calc(69% - 5px);
	}
	.symbaroum.sheet.actor .editable .player .gear .foreground .scrollable {
		margin-top: 5px;
	}
	.symbaroum.sheet.actor .player .bio .appearance .wrapper-left {
		flex: 100%;
		flex-direction: row;
		flex-wrap: nowrap;
	}
	.symbaroum.sheet.actor .player .bio .appearance .wrapper-left .age, .symbaroum.sheet.actor .player .bio .appearance .wrapper-left .height, .symbaroum.sheet.actor .player .bio .appearance .wrapper-left .weight {
		flex: 30%;
		height: 28px;
		margin: 10px 10px 0 0;
	}
	.symbaroum.sheet.actor .player .bio .appearance .wrapper-left .age {
		margin-left: 10px;
	}
	.symbaroum.sheet.actor .player .bio .appearance .wrapper-right {
		flex: 100%;
		margin-left: 10px;
	}
	.symbaroum.sheet.actor .player .bio .appearance label {
		width: 50%;
	}
	.symbaroum.sheet.actor .player .bio .appearance input {
		width: 50%;
		flex-grow: initial;
	}
	.symbaroum.sheet.actor .player .bio .appearance .shadow label {
		width: 30%;
	}
	.symbaroum.sheet.actor .player .bio .appearance .shadow input {
		width: 70%;
	}
	.symbaroum.sheet.actor .player .bio .background, .symbaroum.sheet.actor .player .bio .personal-goal {
		flex: 100%;
	}
}
```
